### PR TITLE
Add BluePill target

### PR DESCRIPTION
**Pull request by Disasm**

### CODE REVIEW

**Review by devanlai — CHANGES_REQUESTED** [review]
Hi, thanks for contributing. I've long thought about making a bluepill target, but I wasn't sure which pins would be best to use. Using the bluepill's own SWCLK/SWDIO pins seems like a reasonable choice to me.

The only thing that I would like to see changed would be to use the dapboot bootloader handoff (as implemented in [`src/stm32f103/stlinkv2-dongle/DFU/DFU.c`](https://github.com/devanlai/dap42/blob/master/src/stm32f103/stlinkv2-dongle/DFU/DFU.c), rather than the STLink/v2-1 bootloader handoff, as I think it's pretty unlikely that anyone will be using the encrypted `STLink/v2-1` bootloader on the bluepill with CMSIS-DAP firmware.

**Comment by Disasm** [comment]
Pins used for BluePill are those used for ST-LINKs on Discovery boards. The only pin changed is for LED. Unlike bluepill's own SWCLK/SWDIO pins, these pins could be used as SPI outputs for better performance.

**Comment by devanlai** [comment]
Thanks for clearing that up - I misread the port. I've merged your changes and added some documentation to the README. The only additional change I had to make was to fix up the USART definition so that it would work.

**Comment by Disasm** [comment]
Thank you!

**Pull request merged**
